databases:
  - name: noshi
    databaseName: noshi
    plan: free
    user: noshi

services:
  - type: redis
    name: noshi-sidekiq-redis
    plan: free
    maxmemoryPolicy: allkeys-lfu
    region: oregon
    ipAllowList: []
  - type: web
    name: noshi
    plan: free
    runtime: ruby
    region: oregon
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: noshi-sidekiq-redis
          property: connectionString
      - fromGroup: noshi
