service: noshi

image: moab/noshi

ssh:
  user: root

servers:
  web:
  - <%= ENV["DEPLOY_SERVER_IP"] %>

proxy:
  ssl:
    certificate_pem: <%= ENV["CLOUDFLARE_SSL_CERT_PEM"] %>
    private_key_pem: <%= ENV["CLOUDFLARE_SSL_KEY_PEM"] %>
  host: noshi.moab.jp
  app_port: 80
  forward_headers: true
  healthcheck:
    path: /up
    interval: 10
    timeout: 30

registry:
  server: <%= ENV["ECR_REGISTRY"] %>
  username: AWS
  password:
  - AWS_ECR_PASSWORD

env:
  secret:
  - SECRET_KEY_BASE
  - CLOUDFLARE_SSL_CERT_PEM
  - CLOUDFLARE_SSL_KEY_PEM

builder:
  arch: amd64

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
